DROP TABLE IF EXISTS expert_reviews_full;

CREATE TABLE big_reviews (
    url TEXT,
    idvscore REAL,
    reviewer TEXT,
    dateP TEXT,
    Rev TEXT,
    WC REAL,
    Analytic REAL,
    Clout REAL,
    Authentic REAL,
    Tone REAL,
    WPS REAL,
    Sixltr REAL,
    Dic REAL,
    function REAL,
    pronoun REAL,
    ppron REAL,
    i REAL,
    we REAL,
    you REAL,
    shehe REAL,
    they REAL,
    ipron REAL,
    article REAL,
    prep REAL,
    auxverb REAL,
    adverb REAL,
    conj REAL,
    negate REAL,
    verb REAL,
    adj REAL,
    compare REAL,
    interrog REAL,
    number REAL,
    quant REAL,
    affect REAL,
    posemo REAL,
    negemo REAL,
    anx REAL,
    anger REAL,
    sad REAL,
    social REAL,
    family REAL,
    friend REAL,
    female REAL,
    male REAL,
    cogproc REAL,
    insight REAL,
    cause REAL,
    discrep REAL,
    tentat REAL,
    certain REAL,
    differ REAL,
    percept REAL,
    see REAL,
    hear REAL,
    feel REAL,
    bio REAL,
    body REAL,
    health REAL,
    sexual REAL,
    ingest REAL,
    drives REAL,
    affiliation REAL,
    achieve REAL,
    power REAL,
    reward REAL,
    risk REAL,
    focuspast REAL,
    focuspresent REAL,
    focusfuture REAL,
    relativ REAL,
    motion REAL,
    space REAL,
    time REAL,
    work REAL,
    leisure REAL,
    home REAL,
    money REAL,
    relig REAL,
    death REAL,
    informal REAL,
    swear REAL,
    netspeak REAL,
    assent REAL,
    nonflu REAL,
    filler REAL,
    AllPunc REAL,
    Period REAL,
    Comma REAL,
    Colon REAL,
    SemiC REAL,
    QMark REAL,
    Exclam REAL,
    Dash REAL,
    Quote REAL,
    Apostro REAL,
    Parenth REAL,
    OtherP REAL
);

-- Drop the table if it already exists
DROP TABLE IF EXISTS expert_reviews_small;

-- Create a new smaller table from the full table
CREATE TABLE expert_reviews_small AS
SELECT
    url,
    reviewer,
    dateP,
    Rev,
    idvscore
FROM expert_reviews_full;



